# Generated by Django 3.2.19 on 2023-07-07 10:52

import ckeditor.fields
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dxwttijho/image/upload/v1687161088/media/profiles/avatar_pnpyxq.png', max_length=255, verbose_name='image')),
                ('bio_user', ckeditor.fields.RichTextField(blank=True, max_length=2500, null=True)),
                ('occupation', models.CharField(default='N/A', max_length=500)),
                ('expertises', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
