# Generated by Django 3.2.19 on 2023-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expertises',
        ),
        migrations.AddField(
            model_name='profile',
            name='expertises',
            field=models.ManyToManyField(blank=True, to='profiles.Expertise'),
        ),
    ]
