# Generated by Django 3.2.19 on 2023-06-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230619_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.expertise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='profileexpertise',
            constraint=models.UniqueConstraint(fields=('profile', 'expertise'), name='unique_profile_expertise'),
        ),
    ]
