# Generated by Django 3.2.19 on 2024-01-07 19:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_banner_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('mas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mas',
            new_name='Mas_event',
        ),
    ]
