# Generated by Django 3.2.19 on 2023-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='contribution_and_originality',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='discussion_and_interpretation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='methodology_and_experimental_design',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='research_objective_and_importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='results_and_data_analysis',
            field=models.IntegerField(default=0),
        ),
    ]
