# Generated by Django 3.2.19 on 2023-05-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230515_1234'),
    ]

    operations = [
    ]
