# Generated by Django 3.2.19 on 2023-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_technique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(default='white', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='technique',
            options={'ordering': ('name',), 'verbose_name_plural': 'Techniques'},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'fundamental'), (2, 'Innovative'), (3, 'Groundbreaking'), (4, 'Insightful'), (5, 'Revolutionary')], default=1),
        ),
    ]
