# Generated by Django 3.2.19 on 2023-07-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230701_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='contribution_and_originality',
            field=models.PositiveIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='discussion_and_interpretation',
            field=models.PositiveIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='methodology_and_experimental_design',
            field=models.PositiveIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='research_objective_and_importance',
            field=models.PositiveIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='results_and_data_analysis',
            field=models.PositiveIntegerField(choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1),
        ),
    ]
